DROP TABLE Narys CASCADE;
DROP TABLE Komanda CASCADE;
DROP TABLE Rungtynes CASCADE;
DROP TABLE Zaidejas CASCADE;
DROP TABLE Treneriu_stabas CASCADE;
DROP TABLE Statistika CASCADE;

DROP VIEW MVP_SMŪGIAI;
DROP VIEW LIBERO;

DROP INDEX KOMANDOSNR;
DROP INDEX Z_POZICIJA;